[tests-only][[full-ci] Added webUI acceptance tests for comments panel visibility
owncloud/guests pull request #546
Opened 2023-02-16 04:00 UTC by roshanlc

## Description
This PR adds test scenarios for the comments panel visibility when the `comments` app is whitelisted and `comments` app is removed from whitelist.

## Related Issue
- Reltated to 
https://github.com/owncloud/guests/issues/523

## Motivation and Context

## How Has This Been Tested?
- Locally
- CI

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-16 04:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/guests?pullRequest=546) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/guests?pullRequest=546) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/guests?pullRequest=546) it.</sub>

2023-02-16 11:14 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		\PHPUnit\Framework\assertContains(
```suggestion
		Assert::assertContains(
```

2023-02-16 11:14 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +	public function theAppShouldBePresentInWhitelistedAppsForGuestAccess(string $appName):void {
can you chekc if (should  | should not) be present step can be combined to one using regex ?

2023-02-16 11:14 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		\PHPUnit\Framework\assertNotContains(
```suggestion
		Assert::assertContains(
```

2023-02-17 07:02 UTC, phil-davis commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +	 * @Then the app :arg1 should not be present in whitelisted apps for guest access
```suggestion
	 * @Then the app :arg1 should not be present in the whitelisted apps for guest access
```

2023-02-17 11:19 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		if (preg_match('/^(be|BE)$/', $state)) {
why not change the $state to lowercase and then you won't have to match for all the possible cases?

2023-02-20 03:56 UTC, saw-jan commented on tests/acceptance/features/webUIGuests/guests.feature
> +    Then the app "comments" should "be" present in the whitelisted apps for guest access
```suggestion
    Then the app "comments" should be present in the whitelisted apps for guest access
```

2023-02-20 04:01 UTC, saw-jan reviewed
This should work

2023-02-20 04:01 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		}
```suggestion
		if (strtolower($state) === "be") {
			Assert::assertContains(
				$appName,
				$appsList,
				"Expected app $appName to be whitelisted for guest access but found it to be missing from whitelist"
			);
		}
		Assert::assertNotContains(
			$appName,
			$appsList,
			"Expected app $appName not to be whitelisted for guest access but found to be included in whitelist"
			);
```

2023-02-20 04:12 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		}
```suggestion
                $state = strtolower($state)
		if (!in_array($state, ["enabled", "disabled"]) {
		    throw new Exception("State must be either 'enabled' or 'disabled' but provided " . $state);
		}
		$this->guestsPage->setLimitGuestAccessToWhiteListedAppsCheckBox($state === "enabled");
```

2023-02-20 11:20 UTC, SwikritiT commented on tests/acceptance/features/webUIGuests/guests.feature
> +    And user "guest@example.com" logs in using the webUI
I think these steps should be `Given`  we aren't really checking if the app can be whitelisted or not.

2023-02-20 11:22 UTC, SwikritiT commented on tests/acceptance/features/webUIGuests/guests.feature
> +    Then the details dialog should be visible on the webUI
And this can be done in a single when step 
something like `When the user opens the details panel of file "<file-name>" using the webUI` or something similar

2023-02-20 11:22 UTC, SwikritiT commented on tests/acceptance/features/webUIGuests/guests.feature
> +    And the "<panel>" details panel should <presence_state> visible
and this can be the then step
```suggestion
    Then the "<panel>" details panel should <presence_state> visible
```

2023-02-21 09:12 UTC, saw-jan commented on tests/acceptance/features/webUIGuests/guests.feature
> +    And user "guest@example.com" logs in using the webUI
guest whitelisted option can be enabled/disabled using the testing API with this step `Given parameter "usewhitelist" of app "guests" has been set to "yes"` But don't about adding the app to the list and getting the whitelisted list.

CC @grgprarup @PrajwolAmatya (If you guys have found out something)

2023-02-22 05:00 UTC, roshanlc commented on tests/acceptance/features/webUIGuests/guests.feature
> +    Then the details dialog should be visible on the webUI
These steps are used in similar fashion across the `webUIFiles/fileDetails.feature` file for checking panels

2023-02-22 06:18 UTC, saw-jan commented on tests/acceptance/features/webUIGuests/guests.feature
> +    And the administrator has "<operation>" app "<app>" to/from the whitelisted apps for guest access
This can be split into two scenarios: comments whitelisted and blacklisted (removed)
Good to have separate scenarios for separate functionalities

2023-02-22 08:38 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +	 * @When /^the administrator "(adds|removes)" app "([^"]*)" to\/from the whitelisted apps for guest access$/
may be we can remove this?

2023-02-22 08:38 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		}
may be this is not need we if we  dont have value adds or removes the step would be undefined.

2023-02-22 08:38 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		}
same here as above

2023-02-22 08:38 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +	 * @Given /^the administrator has "(added|removed)" app "([^"]*)" to\/from the whitelisted apps for guest access$/
also we can remove this?

2023-02-22 08:38 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		}
check not needed ?

2023-02-22 08:38 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +		}
may be check here is also not needed.

2023-02-22 11:00 UTC, SwikritiT commented on tests/acceptance/features/webUIGuests/guests.feature
> +    Then the details dialog should be visible on the webUI
we have a step like `  When the user browses directly to display the "sharing" details of file "<file>" in folder "<folder>"` where the folder can be `/` in this case. can you check if it works? I think this will be cleaner. `filesDetails` is checking different areas of the details panel so it makes sense that the steps are used in that order but here I don't think all those steps are necessary to be present in the scenario.

2023-02-22 11:20 UTC, saw-jan reviewed
:+1:

2023-02-23 03:54 UTC, SagarGi reviewed
LGTM :+1:

2023-02-24 04:29 UTC, amrita-shrestha requested changes

2023-02-24 04:29 UTC, amrita-shrestha commented on tests/acceptance/features/webUIGuests/guests.feature
> +    Then the "comments" details panel should be visible
```suggestion
    And the "comments" details panel should be visible
```

2023-02-24 04:29 UTC, amrita-shrestha commented on tests/acceptance/features/webUIGuests/guests.feature
> +    And the administrator has added app "comments" to/from the whitelisted apps for guest access
I think using one at a time is enough?
```suggestion
    And the administrator has added app "comments" to the whitelisted apps for guest access
```

2023-02-24 04:29 UTC, amrita-shrestha commented on tests/acceptance/features/webUIGuests/guests.feature
> +  Scenario: The comments app is whitelisted for guest access
This scenario title says the comments app is whitelisted for guest app but ` And the administrator has added app "comments" to/from the whitelisted apps for guest access` this step is in Given . Why?

2023-02-24 05:57 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +	}
we can reuse one step definition

2023-02-24 07:20 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/WebUIGuestsContext.php
> +				return $elem !== $appName;
use readable name for $elem
```suggestion
			function (string $elem) use ($appName) {
				return $elem !== $appName;
```

2023-02-28 06:26 UTC, phil-davis commented
@saw-jan I merge the other PR that added some API tests, so there are conflicts now that need to be resolved.

2023-03-02 03:33 UTC, SagarGi reviewed
lgtm :+1:

2023-03-02 04:40 UTC, amrita-shrestha commented on tests/acceptance/features/bootstrap/GuestsContext.php
> +
can't we get this list with the help of API or make it more dynamic?

2023-03-02 04:41 UTC, amrita-shrestha approved these changes
other lgtm

2023-03-02 05:04 UTC, saw-jan commented on tests/acceptance/features/bootstrap/GuestsContext.php
> +
Sadly no. We tried to find APIs and cli commands but didn't find the useful one.
One was `index.php/apps/guests/whitelist` but it returns apps more than that we can see in the actual `whitelist`
i.e. core_apps + default_whitelist_apps

2023-03-06 09:11 UTC, SwikritiT commented on tests/acceptance/features/webUIGuests/guests.feature
> +    And the "comments" details panel should be visible
```suggestion
    And user "guest@example.com" has logged in using the webUI
    And the user has opened the file action menu of file "lorem.txt" on the webUI
    When the user clicks the details file action on the webUI
    Then the details dialog should be visible on the webUI
    And the "comments" details panel should be visible
```

2023-03-07 06:37 UTC, SwikritiT approved these changes
LGTM

2023-03-07 07:08 UTC, merged