fix: respect default_language for guests invitation
owncloud/guests pull request #613
Opened 2024-01-08 11:37 UTC by pako81

## Description
Respect default_language for guests invitation

## Motivation and Context
Currently, the `default_language` config.php option is wrongly not considered when generating templates for guests invitation. This has the consequence that the language of the user creating the guest is rather used, which may not be the same as the one used by the guest (especially true in case of guest users).

Note: the `sendGuestPlainInviteMail` method needed also to be adjusted as this is what is being used when creating a guest directly from custom groups --> https://github.com/owncloud/customgroups/blob/master/lib/Service/GuestIntegrationHelper.php#L124

## How Has This Been Tested?
Set `default_language` in config.php and observe this language is used for guests templates.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-08 12:22 UTC, DeepDiver1975 requested changes

2024-01-08 12:22 UTC, DeepDiver1975 commented on lib/Mail.php
> +		$usedeflanguage = null;
Please use camel case naming
e.g. `$usedDefaultLanguage`

2024-01-08 12:22 UTC, DeepDiver1975 commented on lib/Mail.php
> +		$usedeflanguage = null;
avoid duplication -> extract this to a method

2024-01-08 12:22 UTC, DeepDiver1975 commented on lib/Mail.php
> +		$usedeflanguage = null;
or better make it even part of the `createMailBody`function .....

2024-01-08 16:20 UTC, pako81 commented on lib/Mail.php
> +		$usedeflanguage = null;
Not sure if this can be completely moved into the `createMailBody` function as we need to set the subject and this has to be done inside the `sendGuestInviteMail` and `sendGuestPlainInviteMail` methods. I have extracted the language check to a function to avoid duplication.

2024-01-08 16:34 UTC, DeepDiver1975 requested changes

2024-01-08 16:34 UTC, DeepDiver1975 commented on lib/Mail.php
> +		if ($this->checkDefaultLanguage() !== null) {
`check...()` implies that the function is checking some state or condition and returns true/false

but this function is actually returning some thing - `get...()` fits better

2024-01-08 16:34 UTC, DeepDiver1975 commented on lib/Mail.php
> +		if ($this->checkDefaultLanguage() !== null) {
in addition - let's save cpu cycles and call the method once - save the return in a variable and use it in the if condition and later in the if block as well as in the `createMailBody` argument.

2024-01-08 16:34 UTC, DeepDiver1975 commented on lib/Mail.php
> +		$defaultLang = \OC::$server->getConfig()->getSystemValue('default_language', false);
injection is missing ....

2024-01-08 16:34 UTC, DeepDiver1975 commented on lib/Mail.php
> +		if ($this->checkDefaultLanguage() !== null) {
you can also remove the duplication of the subject generation

```php
$l10n = $this->getDefaultLanguage() ?? $this->l10n;
$subject = (string)$l10n->t('...')

2024-01-08 18:50 UTC, pako81 commented on lib/Mail.php
> +	 * get default_language is defined in config.php
```suggestion
	 * get default_language if defined in config.php
```

2024-01-15 04:53 UTC, phil-davis commented on lib/Mail.php
> +		return $useDefaultLanguage;
```suggestion
		return $defaultLanguage;
```
This is a string in the config like `en_GB` so the var name could be changed so that it does not sound like a boolean.
And add PHPdoc for the return type `?string`

2024-01-15 04:53 UTC, phil-davis commented on lib/Mail.php
> +	private function createMailBody($filename, $link, $passwordLink, $cloudName, $displayName, $expiration, $guestEmail, $overrideL10n = null) {
Add PHP doc for the extra parameter.

2024-01-15 04:53 UTC, phil-davis commented on lib/Mail.php
> +		$useDefaultLanguage = $this->getDefaultLanguage();
```suggestion
		$defaultLanguage = $this->getDefaultLanguage();
```
And adjust the var name in the code.

2024-01-15 04:53 UTC, phil-davis commented on lib/Mail.php
> +		$useDefaultLanguage = $this->getDefaultLanguage();
```suggestion
		$defaultLanguage = $this->getDefaultLanguage();
```
And adjust the var name in the code.

2024-01-17 07:47 UTC, pako81 commented
@phil-davis can you review this again? Thx!

2024-01-17 10:58 UTC, DeepDiver1975 commented
in a perfect world we would cover this with unit tests ...

2024-01-23 15:35 UTC, merged